ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'TEAM_MEMBER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SUPER_ADMIN';

UPDATE "User"
SET role = 'TEAM_MEMBER'
WHERE role IN ('ADMIN', 'MANAGER', 'AGENT');

ALTER TABLE "User" ALTER COLUMN role SET DEFAULT 'TEAM_MEMBER';
